name: laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:13
        env:
          POSTGRES_DB: worldlink
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set environment variables
        run: |
          echo "APP_URL=http://localhost" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=wroldlink" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=admin123" >> .env
          echo "MAIL_MAILER=log" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env



      - name: Generate app key
        run: php artisan key:generate

      - name: Set permissions for storage
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
